/**
 * Pass declaration.
 *
 * Corresponds to nanopass (define-pass name : ilang (arg) -> olang (rv) ...)
 * You write two things: this pass's in/out languages, and rules you care about.
 * Rest generated by framework (nanopass system clause).
 */

import type { LangDecl, NodeOf, Nonterminals, ProdsOf, ProdNode } from "./lang.ts";

// ───────────────────────── Recursion point ─────────────────────────

/** Which nonterminal a tag belongs to. rec dispatches on this. */
type NTOfTag<F, T extends string> = {
  [NT in Nonterminals<F>]: T extends keyof ProdsOf<F, NT> ? NT : never;
}[Nonterminals<F>];

/** All production tags in a language. */
type TagsOf<F> = { [NT in Nonterminals<F>]: keyof ProdsOf<F, NT> & string }[Nonterminals<F>];

/** Handler return: node itself if no extra, tuple if extra declared. */
export type Ret<O, NT extends string, Ctx extends readonly unknown[]> = Ctx extends readonly []
  ? NodeOf<O, NT>
  : readonly [NodeOf<O, NT>, ...Ctx];

/**
 * "Recurse through subtree".
 *
 * Passed to handler by walker (not imported), so handler doesn't pretend to call
 * nonexistent function, nor use global to track "current walker".
 * Corresponds to nanopass's in-place usable named transformer.
 *
 * With extra, returns tuple: first is node, rest is current value after threading extra down.
 */
export type Rec<F, O, Ctx extends readonly unknown[]> = {
  <P extends TagsOf<F>>(
    x: ProdNode<F, P, ProdsOf<F, NTOfTag<F, P>>[P]>,
    ...ctx: Ctx
  ): Ret<O, NTOfTag<F, P>, Ctx>;
  <P extends TagsOf<F>>(
    xs: readonly ProdNode<F, P, ProdsOf<F, NTOfTag<F, P>>[P]>[],
    ...ctx: Ctx
  ): Ctx extends readonly [] ? NodeOf<O, NTOfTag<F, P>>[] : readonly [NodeOf<O, NTOfTag<F, P>>[], ...Ctx];
};

// ───────────────────────── extra: threading down and up ─────────────────────────

/**
 * Values this pass threads down / up.
 *
 *   sig()                  No extra, handler returns node directly
 *   sig(new Map(), 0)      Thread two values down: an environment, a counter
 *
 * **Takes sample values**, not type parameters. Two reasons: types inferred from values
 * (else have to write `pass<typeof L7, typeof L8, [Env, number]>`, too verbose);
 * more importantly, runtime needs **count** to generate threading code, and type
 * parameters don't exist at runtime.
 * Sample values only used for types and count, content not read.
 *
 * "Formal parameters" and "return value" share same shape, threading model requires:
 * extra from one child becomes additional args to next sibling, last one is
 * this node's extra return.
 * (This is nanopass's `,[e free*]` mechanism.)
 */
export interface Sig<Ctx extends readonly unknown[]> {
  readonly __ctx: Ctx;
  /** Runtime-countable arity - codegen uses this to generate threading code. */
  readonly arity: number;
}

export function sig<Ctx extends readonly unknown[]>(...sample: Ctx): Sig<Ctx> {
  return { __ctx: sample, arity: sample.length };
}

// ───────────────────────── Rule types ─────────────────────────

/** Node a rule receives: input language's branch for this nonterminal + tag. */
export type RuleInput<F, NT extends Nonterminals<F>, P extends keyof ProdsOf<F, NT> & string> = ProdNode<
  F,
  P,
  ProdsOf<F, NT>[P]
>;

/**
 * Rule table. Key is nonterminal name, value is productions you handle under it.
 * Return type is same-named nonterminal in output language - consistent with nanopass.
 *
 * ── Why handler return type annotation recommended
 *
 * Annotation now **optional** (not writing won't miss checks, `e2e/type-checks.ts` pins both directions),
 * but **error messages differ by order of magnitude**:
 *
 *     With annotation:    TS2322: Type '"Var"' is not assignable to type '"Prog"'.
 *                         TS2739: Type '{ type: "Prog"; }' is missing the following properties …
 *     Without annotation: TS2719: … Two different types with this name exist, but they are unrelated.
 *                         Or TS2322 dumping entire `MergeRules<MergeRules<…>>` chain
 *
 * Difference is what TS compares: without annotation, compares two **separately instantiated**
 * `Rules<…>`, which embed full language declaration shape, so "doesn't recognize itself";
 * with annotation, degrades to comparing nodes themselves.
 */
export type Rules<F, O, Ctx extends readonly unknown[] = []> = {
  readonly [NT in Nonterminals<F>]?: {
    readonly [P in keyof ProdsOf<F, NT> & string]?: (
      n: RuleInput<F, NT, P>,
      rec: Rec<F, O, Ctx>,
      ...ctx: Ctx
    ) => Ret<O, NT, Ctx>;
  };
};

export interface Pass<F extends LangDecl, O extends LangDecl, Ctx extends readonly unknown[] = []> {
  readonly from: F;
  readonly to: O;
  readonly rules: Rules<F, O, Ctx>;
  /** How many values threaded down / up. Codegen uses this for threading code. */
  readonly arity: number;
  /** Initial values for extra (fresh copy per run). */
  readonly init?: (() => Ctx) | undefined;
  /** Input language entry node → output language entry node.
   *  extra is **internal** communication of this pass (corresponds to nanopass processor's
   *  extra return), so pass as a whole is still "node in, node out" - extra discarded here. */
  readonly run: (input: NodeOf<F, F["entry"]>) => NodeOf<O, O["entry"]>;
}

export function pass<
  const F extends LangDecl,
  const O extends LangDecl,
  const Ctx extends readonly unknown[] = [],
>(spec: {
  readonly from: F;
  readonly to: O;
  readonly sig?: Sig<Ctx>;
  /** Initial values fed to extra at entry. Factory function - each run needs fresh copy,
   *  else mutable container (e.g. environment) shared between runs. */
  readonly init?: () => Ctx;
  /**
   * ── `NoInfer` is the only critical word here (t24)
   *
   * It **brakes inference**: makes TS infer `F` / `O` / `Ctx` only from
   * `from` / `to` / `sig` - which is what it should do, they're **explicitly written**.
   *
   * Without it: TS tries to infer output language from handler **return position**,
   * which is `Ret<O, NT, Ctx>` = `[NodeOf<O, NT>, …]` - `NodeOf` is mapped type.
   * **Inferring from mapped type** explodes: TS2589 (type instantiation too deep)
   * when handler lacks return annotation.
   * "Rule on `Program` + this pass has `sig`" easily triggers it, which happens to be
   * most common compiler pattern "scan top-level definitions".
   *
   * Root cause always this, **not "language is 6-7 derive layers"** - trampled record
   * blamed it on `MergeRules<…>` chain. 0 layers (pure `language()` literal, `Lsrc`)
   * explodes same way, tested: 0/1/2/3/6 layers in `scratch/` (reproduction script) all explode.
   */
  readonly rules: NoInfer<Rules<F, O, Ctx>>;
}): Pass<F, O, Ctx> {
  return {
    from: spec.from,
    to: spec.to,
    rules: spec.rules,
    arity: spec.sig?.arity ?? 0,
    init: spec.init,
    run: () => {
      throw new Error("pass.run generated by codegen");
    },
  };
}
