/**
 * Pipeline declaration.
 *
 * Order is human-written - no guessing, no folder scanning, no inferring from filenames.
 * Linker's job is **validation**.
 * Checks that can go in types are pushed there, so errors caught by tsc, not waiting for link.
 */

import type { LangDecl, NodeOf } from "./lang.ts";
import type { Pass } from "./pass.ts";

// ───────────────────────── Type-level: chain ─────────────────────────

type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false;

type PassLike = { readonly from: LangDecl; readonly to: LangDecl };

/** passes[i].to must equal passes[i+1].from. */
export type ChainOk<P extends readonly PassLike[]> = P extends readonly []
  ? true
  : P extends readonly [infer H, ...infer T]
    ? H extends PassLike
      ? T extends readonly PassLike[]
        ? T extends readonly []
          ? true
          : T extends readonly [infer N, ...infer _]
            ? N extends PassLike
              ? Equal<H["to"], N["from"]> extends true
                ? ChainOk<T>
                : false
              : false
            : false
        : false
      : false
    : false;

/** entry must equal first pass's from. */
export type EntryOk<E extends LangDecl, P extends readonly PassLike[]> = P extends readonly [
  infer H,
  ...infer _,
]
  ? H extends PassLike
    ? Equal<E, H["from"]>
    : false
  : true;

/** Last pass in chain, used to compute pipeline's output language. */
export type Last<P extends readonly PassLike[]> = P extends readonly []
  ? never
  : P extends readonly [infer H, ...infer T]
    ? T extends readonly []
      ? H
      : Last<T & readonly PassLike[]>
    : never;

type Broken = {
  readonly "pass chain broken: entry must equal passes[0].from, and passes[i].to must equal passes[i+1].from": never;
};

type Check<E extends LangDecl, P extends readonly PassLike[]> =
  ChainOk<P> extends true ? (EntryOk<E, P> extends true ? unknown : Broken) : Broken;

// ───────────────────────── Declaration ─────────────────────────

export interface Pipeline<E extends LangDecl, P extends readonly PassLike[]> {
  readonly entry: E;
  readonly passes: P;
  /** Entry node → last pass's output node. Generated by codegen. */
  readonly run: (input: NodeOf<E, E["entry"]>) => unknown;
}

/**
 *   export default pipeline({
 *     entry: Lsrc,
 *     passes: [removeOneArmedIf, ...],
 *   });
 */
export function pipeline<const E extends LangDecl, const P extends readonly PassLike[]>(
  spec: { readonly entry: E; readonly passes: P } & Check<E, P>,
): Pipeline<E, P> {
  return {
    ...spec,
    run: () => {
      throw new Error("pipeline.run generated by codegen");
    },
  };
}
